### ISSUE TITLE
Import DL WAD onto UYA base map not working

### ISSUE THREAD

**Issue by badger41** [Dnawrkshp/horizon-forge#2]
Trying to import a DL WAD into a UYA base map is creating an empty map render object and doing nothing else. No errors are reported in the console.

![Unity_QL4RC25Y9Q](https://github.com/user-attachments/assets/0264aa95-7f84-444c-9d3f-a46293f7ac18)

**Comment by Dnawrkshp** [comment]
![image](https://github.com/user-attachments/assets/dd6f46f1-77e1-4d8f-82fc-f6b8f9fad6f5)
lmao
