### ISSUE TITLE
Cant import maps without skybox textures

### ISSUE THREAD

**Issue by badger41** [Dnawrkshp/horizon-forge#8]
Forge can't import maps that dont have skybox textures, it fails and there's no option to skip skybox importing

Example:
MP Command Center

![Unity_rxIxoElhLy](https://github.com/user-attachments/assets/2702304f-99cf-4faf-b7a7-5ee21a0d3ac1)

**Comment by Dnawrkshp** [comment]
Fixed dbc6155ede0db4f2aa7a95f7bb309ebaa6ea7130
